# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{adminsite}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Liborio Cannici"]
  s.date = %q{2010-05-05}
  s.description = %q{Adminsite plugin}
  s.email = %q{lic@crd.dk}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "app/controllers/admin/admins_controller.rb",
     "app/controllers/admin/base_controller.rb",
     "app/controllers/admin/file_assets_controller.rb",
     "app/controllers/admin/pages_controller.rb",
     "app/controllers/admin_application_controller.rb",
     "app/controllers/admin_sessions_controller.rb",
     "app/controllers/contents_controller.rb",
     "app/helpers/admin/adminsite_application_helper.rb",
     "app/helpers/admin_application_helper.rb",
     "app/models/admin.rb",
     "app/models/admin_session.rb",
     "app/models/file_asset.rb",
     "app/models/page.rb",
     "app/views/admin/admins/edit.html.haml",
     "app/views/admin/admins/index.html.haml",
     "app/views/admin/admins/new.html.haml",
     "app/views/admin/file_assets/index.html.haml",
     "app/views/admin/pages/edit.html.haml",
     "app/views/admin/pages/index.html.haml",
     "app/views/admin/pages/new.html.haml",
     "app/views/admin/shared/_menu.haml",
     "app/views/admin_sessions/new.html.haml",
     "app/views/layouts/admin.html.haml",
     "config/routes.rb",
     "db/migrate/20100303115059_create_admins.rb",
     "db/migrate/20100304115407_create_sessions.rb",
     "db/migrate/20100304120229_add_open_id_authentication_tables.rb",
     "db/migrate/20100304121909_create_file_assets.rb",
     "db/migrate/20100304122722_create_pages.rb",
     "lib/adminsite.rb",
     "lib/adminsite/tasks.rb",
     "public/images/admin/accept.png",
     "public/images/admin/add.png",
     "public/images/admin/back_top.gif",
     "public/images/admin/cross.png",
     "public/images/admin/logo.gif",
     "public/images/admin/logo.png",
     "public/images/admin/newspaper_add.png",
     "public/images/admin/newspaper_delete.png",
     "public/images/admin/openid-icon-small.gif",
     "public/images/admin/pencil.png",
     "public/images/admin/rails.png",
     "public/images/admin/spinner.gif",
     "public/images/admin/tableftB.gif",
     "public/images/admin/tabrightB.gif",
     "public/images/rails.png",
     "public/stylesheets/admin.css",
     "tasks/adminsite_tasks.rake"
  ]
  s.homepage = %q{}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Adminsite}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<authlogic>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<paperclip-cloudfiles>, [">= 0"])
    else
      s.add_dependency(%q<authlogic>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<paperclip-cloudfiles>, [">= 0"])
    end
  else
    s.add_dependency(%q<authlogic>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<paperclip-cloudfiles>, [">= 0"])
  end
end

